TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += khly6517.db
DATA += khly6517.proto

#=======================================
include $(TOP)/configure/RULES
